### ISSUE TITLE
Windows S3 Sync Error

### ISSUE THREAD

**Issue by rtselizondo** [clowdhaus/aws-github-actions#4]
### Describe the bug

I'm getting the below error message when doing an s3 sync with the Windows runner os. 

```
Run clowdhaus/aws-github-actions/packages/s3_sync@master
  with:
    local-path: dist/
    bucket-name: %%Secret%%
    path-prefix: bin/refs/heads/pipeline
  env:
    AWS_ACCESS_KEY_ID: ***
    AWS_SECRET_ACCESS_KEY: ***
    AWS_DEFAULT_REGION: us-east-1
    AWS_REGION: us-east-1
##[error]Unable to locate executable file: C:\Program. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also verify the file has a valid extension for an executable file.
```

### To Reproduce

Create github action for s3 sync on windows runner. 

```
- name: Upload Binaries
        if: startsWith(matrix.os, 'windows') 
        uses: clowdhaus/aws-github-actions/packages/s3_sync@master
        with:
          local-path: dist/
          bucket-name: %%Secret%%
          path-prefix: bin/${runner.os}/
```
Run the action and see the error. 

### Expected behavior

Expected behavior is sync action will complete without error.

## Environment:

- OS: Windows
- Version: Github Runner
