### ISSUE TITLE
Error on Github action

### ISSUE THREAD

**Issue by ZsoltPath** [clowdhaus/aws-github-actions#7]
### Describe the bug

Getting `##[error]Unable to locate executable file: aws. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.` error when running action on Github shared runners

### To Reproduce

Set up GH action
```
      - name: deploy
        uses: clowdhaus/aws-github-actions/packages/s3_sync@v0.4.4
        with:
          local-path: build/
          bucket-name: ${{ env.BUCKET }}
          args: --cache-control "max-age=3600" --exclude "service-worker.js" --exclude "*manifest.json" --exclude "*.html"
```

### Expected behavior

Bucket updated.

## Environment (please complete the following information):

Github shared action runner
